[[main]]
    name = "Posts"
    pageRef = "posts"
    weight = 10

[[main]]
    name = "Veeam"
    url = "/categories/veeam/"
    weight = 30

[[main]]
    name = "Virtualization"
    url = "/categories/virtualization/"
    weight = 40

[[main]]
    name = "Presentations"
    url = "/categories/presentations/"
    weight = 50