  colorScheme = "github"
  defaultAppearance = "dark"
  autoSwitchAppearance = false

  [homepage]
    layout = "page"
    showRecent = true
    recentLimit = 7

  [article]
    showDate = true
    showAuthor = true
    showReadingTime = true
    showTags = true

  [list]
    showSummary = true

  [taxonomy]
    showTermCount = true

  [author]
    name = "Jim Jones"
    headline = "Infra nerd. Cloud, VMs, and automation."
    bio = ""
    links = [
        {github = "https://github.com/k00laidIT"},
        {linkedin = "https://www.linkedin.com/in/k00laidIT"},
        {twitter = "https://twitter.com/k00laidIT"},
        {bluesky = "https://bsky.app/profile/koolaid.info"},
        {instagram = "https://www.instagram.com/k00laidIT"},
        {reddit = "https://www.reddit.com/user/k00laidIT/"},
    ]

    [footer]
      showThemeAttribution = false
      showScrollToTop = true
      showSocial = true