  colorScheme = "github"
  disableTextInHeader = true
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  logo = "img/koolaid-round.png"
  enableCodeCopy = true
  enableSearch = true

  [homepage]
    layout = "page"
    showRecent = true
    recentLimit = 7

  [article]
    showDate = true
    showAuthor = true
    showAuthorBottom = true
    showReadingTime = true
    showWordCount = false
    showTaxonomies = true
    showHero = true
    heroStyle = "basic"
    showPagination = false
    showRelatedContent = true
    relatedContentLimit = 3
    sharingLinks = ["linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]

  [list]
    showSummary = true

  [taxonomy]
    showTermCount = true

  [author]
    name = "Jim Jones"
    headline = ""
    bio = ""
    # image = "img/jim.jpg"
    links = [
        {github = "https://github.com/k00laidIT"},
        {linkedin = "https://www.linkedin.com/in/k00laidIT"},
        {twitter = "https://twitter.com/k00laidIT"},
        {bluesky = "https://bsky.app/profile/koolaid.info"},
        {instagram = "https://www.instagram.com/k00laidIT"},
        {rss = "https://dev.koolaid.info/posts/index.xml"},
    ]

# config/_default/params.toml

[umamiAnalytics]
  websiteid = "27abc18f-48be-4f7f-a5b6-09c28a9a15cc"  
  enableTrackEvent = true

[footer]
  showThemeAttribution = false
  showScrollToTop = true
  showAppearanceSwitcher = false